### PR TITLE
README.rst: pycon highlight ipython sessions

### PR DESCRIPTION
**Pull request by msabramo**
I think PyPI will render these specially. I'm working on adding support to GitHub and Atom (see https://github.com/atom/language-python/pull/48)

### CODE REVIEW

**Comment by jwass** [comment]
Thanks @msabramo 

I uploaded a version of this to testpypi: 
https://testpypi.python.org/pypi?:action=display&name=enviro&version=0.0.2

Compare with the current version:
https://pypi.python.org/pypi?:action=display&name=enviro&version=0.0.1

It renders the IPython sessions as a light gray. I think I prefer the current version which is just black text.
Thoughts??

**Comment by msabramo** [comment]
Yeah it doesn't look good. I'd drop it. Maybe Pygments doesn't support the IPython prompt. The grammar I did for GitHub does.

**Comment by jwass** [comment]
OK. Thanks!

P.S. Any idea why this one doesn't render?
https://pypi.python.org/pypi?:action=display&name=geojsonio&version=0.0.1

from: https://github.com/jwass/geojsonio.py

**Comment by msabramo** [comment]
See https://bitbucket.org/pypa/pypi/pull-request/60/fix-bb-214-make-rst-rendering-not-fail-for/diff

**Pull request closed without merging**
